---
title: "Palmer Penguins"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(palmerpenguins)
library(knitr)
library(ggplot2)
library(dplyr)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Stats summary of penguins

```{r}
knitr::kable(summary(penguins),
              caption = "Summary Stats of Penguins")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Regression of Bill Depth by Length

```{r}
ggplot(penguins,
       aes(x = bill_length_mm,
           y = bill_depth_mm)) +
  geom_point() +
  geom_smooth(method = "lm")
```

### Correlations of Bill Length, Depth and Flipper Length

```{r}
library(GGally)
penguins %>%
  select(species,
         bill_length_mm,
         bill_depth_mm,
         flipper_length_mm) %>%
  GGally::ggpairs(mapping = aes(color = species))
```

